# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - terence-docker-2

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: 'ubuntu-latest'

steps:
- uses: actions/checkout@v2

- name: Set up Docker Buildx
   uses: docker/setup-buildx-action@v1

- name: Log in to registry
uses: docker/login-action@v1
with:
registry: https://terenceregistry.azurecr.io/
username: ${{ secrets.AzureAppService_ContainerUsername_5bccac3f1bb34a0a838df1e19a512ebe }}
password: ${{ secrets.AzureAppService_ContainerPassword_5340843781fb4b8aa5d858498a4015bd }}

- name: Build and push container image to registry
uses: docker/build-push-action@v2
with:
push: true
tags: terenceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bccac3f1bb34a0a838df1e19a512ebe }}/terenceocto/cicd-buzz:${{ github.sha }}
file: ./Dockerfile

deploy:
runs-on: ubuntu-latest
needs: build
environment:
name: 'production'
url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

steps:
- name: Deploy to Azure Web App
id: deploy-to-webapp
uses: azure/webapps-deploy@v2
with:
app-name: 'terence-docker-2'
slot-name: 'production'
publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bdced2d5466440eb7a123b6aea1d1c6 }}
images: 'terenceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5bccac3f1bb34a0a838df1e19a512ebe }}/terenceocto/cicd-buzz:${{ github.sha }}'
